apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: rsfs-any-allow-rsfs-shared-ns-g-np
  labels:
    {{- include "ch03-nonprd-c1.labels" . | nindent 4}}
  {{- with .Values.rsfs.labels}}
  {{- toYaml . | nindent 4}}
  {{- end}}
  {{- with .Values.rsfsshared.labels}}
  {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  namespaceSelector: has(field.cattle.io/projectId) && field.cattle.io/projectId in { "{{.Values.rsfsshared.dev.rancherProjectID}}" }
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: has(field.cattle.io/projectId) && field.cattle.io/projectId in {"{{.Values.rsfs.dev.rancherProjectID}}"}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: has(field.cattle.io/projectId) && field.cattle.io/projectId in {"{{.Values.rsfs.dev.rancherProjectID}}"}
